server_location: 'https://matrix.org'
shared_secret: 'RegistrationSharedSecret'
db: 'db.sqlite3'
port: 5000
logger:
  level: 'INFO' # DEBUG, INFO, WARNING, ERROR
  format: '[%(asctime)s] [%(levelname)s@%(name)s] %(message)s'
  file: 'm_reg.log'
# password requirements
password:
  min_length: 8
